# -*- coding: utf-8 -*-
"""Curated word data for Lessons 17 (Outsiders Ch.1-2) and 18 (Outsiders Ch.3-5)."""

LESSON_17 = [
    dict(word='reckless', pos='adj.', definition='Without caution or concern for consequences; careless.',
         ex="Dally's reckless streak got him arrested more than once, but Ponyboy admired how fearless he seemed.",
         syns=['careless', 'rash', 'foolhardy', 'heedless', 'daredevil'],
         ants=['careful', 'cautious', 'prudent', 'wary'],
         simile=["a boy who lights a match just to see how close he can hold it to his own sleeve",
                 "someone who jaywalks across a highway without ever once checking for traffic"],
         metaphor="Reckless is not a warning label — it is a dare Dally makes to the world every single day.",
         prompt="Describe a reckless decision a character in The Outsiders makes. What consequence follows?"),
    dict(word='unfathomable', pos='adj.', definition='Not able to be imagined or understood.',
         ex="For some unfathomable reason, Dally loved fights, blondes, and school — three things that never seemed to fit together.",
         syns=['incomprehensible', 'inconceivable', 'unimaginable', 'baffling', 'mysterious'],
         ants=['understandable', 'clear', 'obvious', 'comprehensible'],
         simile=["trying to read a letter written in a language no one in the gang ever learned",
                 "a math problem with no numbers, only a question mark where the answer should be"],
         metaphor="Unfathomable is not a mystery you can solve — it is a locked door with no keyhole anyone has found.",
         prompt="Write about something you find unfathomable — a decision, a rule, or an event you simply can't wrap your head around."),
    dict(word='outfit', pos='n.', definition='A group organized to carry out a particular activity, especially of a military or business nature.',
         ex="Tim Shepard's outfit ran the downtown streets the way Darry's gang ran their own turf.",
         syns=['gang', 'crew', 'squad', 'band', 'organization'],
         ants=['individual', 'loner'],
         simile=["a pack of wolves that decided long ago never to hunt alone",
                 "a team that shows up to every fight already wearing matching jackets"],
         metaphor="An outfit is not just a group of friends — it is a shield the greasers wear made of each other.",
         prompt="Describe a group or “outfit” you belong to (a team, a family, a club). What holds it together?"),
    dict(word='gingerly', pos='adv.', definition='In a careful or cautious manner; warily.',
         ex="Ponyboy touched his bruised cheek gingerly, half expecting the pain to be worse than it was.",
         syns=['cautiously', 'warily', 'delicately', 'tentatively'],
         ants=['carelessly', 'recklessly', 'roughly'],
         simile=["a boy testing ice on a pond one small step at a time, ready to jump back the second it cracks",
                 "someone lifting a lid off a pot they're pretty sure is still boiling"],
         metaphor="Gingerly is not a way of touching something — it is the question “will this hurt?” asked with your hands instead of your mouth.",
         prompt="Describe a time you did something gingerly — carefully, because you weren't sure it was safe."),
    dict(word='sagely', pos='adv.', definition='Wisely, in a knowing way.',
         ex="Two-Bit nodded sagely, as if bruises were something he'd studied his whole life.",
         syns=['wisely', 'knowingly', 'shrewdly', 'judiciously'],
         ants=['foolishly', 'unwisely', 'naively'],
         simile=["an old man who has watched the same fight a hundred times and already knows how it ends",
                 "a coach who nods at a mistake because he made the exact same one years ago"],
         metaphor="Sagely is not just a nod — it is a whole lecture Two-Bit delivers without saying a single word.",
         prompt="Think of someone who always seems to nod sagely, like they already know how things will turn out. What makes them seem so wise?"),
    dict(word='savvy', pos='v.', definition='To understand or get the sense of (an idea, etc.).',
         ex="“He loves you a lot — savvy?” Soda asked, making sure Ponyboy understood before he let the subject drop.",
         syns=['understand', 'comprehend', 'grasp', 'follow'],
         ants=['misunderstand', 'miss', 'confuse'],
         simile=["a lock finally accepting the right key after every other one has failed",
                 "a radio station tuning in clearly after nothing but static"],
         metaphor="To savvy something is not to hear it — it is to feel the click when the idea finally fits.",
         prompt="Describe an idea that took you a while to savvy — to actually understand. What finally made it click?"),
    dict(word='roguishly', pos='adv.', definition='In a good-naturedly mischievous way.',
         ex="Dally grinned roguishly at Cherry, daring her to be annoyed with him.",
         syns=['mischievously', 'impishly', 'playfully', 'slyly'],
         ants=['solemnly', 'seriously', 'innocently'],
         simile=["a cat that just knocked something off the table and is watching to see if you'll laugh",
                 "a kid handing back a joke they know is a little too bold, grinning the whole time"],
         metaphor="A roguish grin is not an apology — it is Dally's way of saying trouble is more fun when you smile through it.",
         prompt="Describe someone you know who acts roguishly — mischievous, but never mean about it."),
    dict(word='briskly', pos='adv.', definition='In an active, energetic, or lively way; quickly.',
         ex="Cherry answered Ponyboy's question briskly, changing the subject before Marcia could bring up Sodapop again.",
         syns=['quickly', 'energetically', 'swiftly', 'promptly'],
         ants=['slowly', 'sluggishly', 'lazily'],
         simile=["a wind that changes direction the second it feels a conversation drift somewhere uncomfortable",
                 "a cashier ringing up a line that's gotten too long for small talk"],
         metaphor="Briskly is not just fast — it is a door closing on a question before anyone can walk through it.",
         prompt="Describe a time you walked or spoke briskly — quickly and with purpose. What were you trying to avoid or get to?"),
    dict(word='wince', pos='v.', definition='To shrink suddenly back or away, as from pain or distress; flinch.',
         ex="Ponyboy winced inside every time someone brought up Sodapop dropping out of school.",
         syns=['flinch', 'cringe', 'recoil', 'shrink back'],
         ants=['relax', 'stand firm'],
         simile=["a hand pulled back from a stove half a second before it even touches the metal",
                 "a kid closing their eyes before the dodgeball even leaves the other player's hand"],
         metaphor="A wince is not a movement — it is the body's own way of ducking a punch the words already threw.",
         prompt="Describe something that always makes you wince — flinch — even just thinking about it."),
    dict(word='stride', pos='v.', definition='To walk with long, even steps, as in an energetic or showy way.',
         ex="Dally crossed the lot with a stride so confident it looked like the whole place already belonged to him.",
         syns=['march', 'pace', 'step out'],
         ants=['shuffle', 'amble', 'trudge'],
         simile=["someone crossing a stage they've already decided is theirs before the audience has made up its mind",
                 "a captain walking the deck of a ship they built with their own hands"],
         metaphor="To stride is not to walk — it is to announce, with every step, that you were never asking for permission.",
         prompt="Describe a time you strode into a room — walked in confidently, like you owned the place."),
    dict(word='incredulous', pos='adj.', definition='Indicating or showing disbelief.',
         ex="Cherry gave Dally an incredulous look, as if his nerve was the most surprising thing she'd seen all night.",
         syns=['disbelieving', 'skeptical', 'doubtful', 'unconvinced'],
         ants=['credulous', 'trusting', 'convinced'],
         simile=["a scoreboard that refuses to update because the number on it doesn't seem possible",
                 "a teacher rereading a test answer twice, sure it must be a typo"],
         metaphor="An incredulous look is not confusion — it is a question your whole face asks without a single word.",
         prompt="Describe something that left you incredulous — so surprising you almost couldn't believe it."),
    dict(word='scowl', pos='v.', definition='To make an angry frown.',
         ex="Dallas scowled for a second before he got up and stalked off without another word.",
         syns=['frown', 'glower', 'glare', 'grimace'],
         ants=['smile', 'beam', 'grin'],
         simile=["a sky going gray the second before a storm finally decides to happen",
                 "a teacher's face when a joke lands at exactly the wrong moment"],
         metaphor="A scowl is not just a face — it is a warning sign nailed up seconds before the door slams.",
         prompt="Describe a moment when someone scowled at you or someone else. What caused it?"),
    dict(word='stalk', pos='v.', definition='To walk with measured, stiff, or haughty strides.',
         ex="His fists jammed in his pockets, Dally stalked off and didn't come back that night.",
         syns=['strut', 'march stiffly', 'storm off'],
         ants=['shuffle', 'saunter', 'amble'],
         simile=["a soldier leaving a battlefield he refuses to admit he lost",
                 "a cat stiff-legged and furious, tail low, done with the conversation entirely"],
         metaphor="To stalk off is not to leave — it is to carry the whole argument away with you, still burning.",
         prompt="Describe a time you or someone you know stalked off — stormed away, stiff and angry, from an argument."),
    dict(word='stricken', pos='adj.', definition='Deeply affected, as with grief, fear, or other emotions.',
         ex="Steve's stricken expression told Ponyboy something was terribly wrong before anyone said a word.",
         syns=['devastated', 'anguished', 'overwhelmed', 'afflicted'],
         ants=['unaffected', 'untouched', 'composed'],
         simile=["a house with all its lights suddenly out at once, the whole shape of it gone dark",
                 "a radio that goes silent mid-song and never explains why"],
         metaphor="Stricken is not an expression — it is grief arriving on someone's face before their voice can catch up.",
         prompt="Describe a moment you felt stricken — deeply and suddenly affected by grief, fear, or shock."),
]

LESSON_18 = [
    dict(word='grimly', pos='adv.', definition='Firmly and cheerlessly, without giving rise to hope of change of mind or fate.',
         ex="“And,” Two-Bit added grimly, “a few other of the socially elite checkered-shirt set.”",
         syns=['sternly', 'bleakly', 'somberly', 'severely'],
         ants=['cheerfully', 'brightly', 'warmly'],
         simile=["a judge reading a sentence he already knows nobody in the room wants to hear",
                 "a coach announcing the score at halftime when everyone already knows it's bad"],
         metaphor="Grimly is not a tone of voice — it is bad news arriving before the sentence even finishes.",
         prompt="Describe a moment when someone delivered news grimly — seriously, without any hope things would get better."),
    dict(word='quiver', pos='v.', definition='To shake with very small, quick movements.',
         ex="Ponyboy's breath came in quivering sobs as he admitted to Johnny that he was scared.",
         syns=['tremble', 'shake', 'shudder', 'shiver'],
         ants=['stay still', 'steady'],
         simile=["a candle flame in a room where someone just opened a door they shouldn't have",
                 "a leaf still shaking on a branch long after the wind has passed"],
         metaphor="A quiver is not just a shake — it is fear leaking out through the body when the voice won't say it out loud.",
         prompt="Describe a time your voice or hands quivered — shook — because you were scared or upset."),
    dict(word='unceasingly', pos='adv.', definition='Without pause or respite; continuous.',
         ex="“My teeth chattered unceasingly, and I couldn't stop them,” Ponyboy admits, hiding in the old church.",
         syns=['continuously', 'ceaselessly', 'endlessly', 'relentlessly'],
         ants=['occasionally', 'intermittently', 'briefly'],
         simile=["rain that never once checks the clock to see if it's been raining too long",
                 "a clock ticking in an empty house, running whether anyone hears it or not"],
         metaphor="Unceasingly is not a length of time — it is a clock with the hands removed so it can never claim to be done.",
         prompt="Describe something that seems to happen unceasingly — without ever stopping — in your own life."),
    dict(word='absently', pos='adv.', definition='In an absent-minded manner; inattentively.',
         ex="“I wish I was home,” Ponyboy thought absently, half-asleep and half-somewhere else entirely.",
         syns=['distractedly', 'inattentively', 'vacantly', 'dreamily'],
         ants=['attentively', 'alertly', 'mindfully'],
         simile=["someone answering a question while their eyes are already halfway out the window",
                 "a student nodding along to a lecture that stopped registering ten minutes ago"],
         metaphor="Absently is not forgetting — it is a mind that quietly stepped out of the room and left the body to answer the door.",
         prompt="Describe a time you did something absently — without really paying attention, your mind somewhere else."),
    dict(word='imploringly', pos='adv.', definition='In a way that expresses urgent pleading, begging.',
         ex="Ponyboy looked at Johnny imploringly, hoping he wouldn't have to cut his hair alone.",
         syns=['pleadingly', 'beseechingly', 'desperately'],
         ants=['indifferently', 'dismissively', 'coldly'],
         simile=["a dog sitting by the table during dinner, sure that this time the answer will be yes",
                 "a kid holding up a permission slip a half second before the deadline"],
         metaphor="An imploring look is not a request — it is a whole argument made with just the eyes, because the mouth is too afraid to lose.",
         prompt="Describe a time you looked at someone imploringly — begged with your eyes — hoping they'd say yes."),
    dict(word='reluctantly', pos='adv.', definition='Without really wanting to, unwillingly.',
         ex="“Gee, thanks,” Ponyboy said, and put the book down reluctantly, wishing he had more time to read it.",
         syns=['unwillingly', 'hesitantly', 'grudgingly', 'half-heartedly'],
         ants=['eagerly', 'willingly', 'readily'],
         simile=["a kid handing over the last slice of cake, doing the math on how fast they could grab it back",
                 "someone letting go of a rope in tug-of-war only because their hands finally gave out"],
         metaphor="Reluctantly is not slowness — it is a yes that your hands agree to before your heart has actually signed off on it.",
         prompt="Describe something you did reluctantly — unwillingly — even though you knew you had to do it."),
    dict(word='gallant', pos='adj.', definition='Brave, spirited, noble-minded, or chivalrous.',
         ex="Johnny thought the soldiers in the poem were gallant, riding into sure death — and it reminded him of Dally.",
         syns=['brave', 'courageous', 'heroic', 'noble'],
         ants=['cowardly', 'timid', 'craven'],
         simile=["a knight who rides toward the danger everyone else is already running from, and never once looks back",
                 "a firefighter walking into the smoke while everyone else is walking out"],
         metaphor="Gallant is not a compliment — it is what people call you after you've already decided the risk was worth it.",
         prompt="Describe someone — real or fictional — who acted gallantly. What brave or noble thing did they do?"),
    dict(word='elude', pos='v.', definition='To avoid or escape the understanding of.',
         ex="The meaning of the poem eluded Ponyboy at first, even though he never forgot the lines.",
         syns=['escape', 'evade', 'baffle', 'slip away from'],
         ants=['clarify', 'reveal itself to'],
         simile=["a word sitting right on the tip of your tongue that vanishes the second you try to say it",
                 "a math problem that makes perfect sense right up until you try to write down the answer"],
         metaphor="To elude understanding is not to hide — it is a meaning that keeps one step ahead of you no matter how fast you follow.",
         prompt="Describe something whose meaning eluded you at first — that you didn't understand right away."),
    dict(word='indignant', pos='adj.', definition='Feeling or showing anger about something considered to be unfair or without value.',
         ex="“You're starved?” Johnny was so indignant he nearly squeaked, offended that anyone would think otherwise.",
         syns=['outraged', 'offended', 'resentful', 'incensed'],
         ants=['content', 'pleased', 'satisfied'],
         simile=["a kid who did all the chores watching someone else take the credit at dinner",
                 "a player pulled from the game the one time they were finally about to score"],
         metaphor="Indignant is not just angry — it is fairness itself slamming its fist on the table and demanding to be heard.",
         prompt="Describe a time you felt indignant — angry because something seemed completely unfair."),
    dict(word='bewilder', pos='v.', definition='To confuse or puzzle.',
         ex="“Sodapop?” Ponyboy said, bewildered, unable to figure out how his brother could possibly know.",
         syns=['confuse', 'puzzle', 'perplex', 'mystify'],
         ants=['clarify', 'enlighten', 'inform'],
         simile=["someone handed a map with no streets labeled and told to find their way home anyway",
                 "a substitute teacher trying to follow directions left by three different people"],
         metaphor="Bewildered is not confusion — it is the moment the ground you were standing on turns out to be a question instead of an answer.",
         prompt="Describe a time you felt bewildered — completely confused or puzzled by something."),
]
