# -*- coding: utf-8 -*-
"""Builds the injected 'Test Practice' 3-part mode (Synonym Match /
Fill-in-the-Blank / Answer the Question) matching the new grade-7 test
rubric (see pdfs/grade 7/Vocab Test Prep - Strategies and Test Format.pdf).
Returns (css, screens_html, start_button_html, script_js) to splice into
the page generated by generate_lesson.build_html().
"""
import json


def build_practice_block(acc, dark, rgba_star, words):
    prompts_js = json.dumps({w['word']: w['prompt'] for w in words}, ensure_ascii=False)

    css = f"""
.practice-menu{{max-width:520px;width:100%}}
.practice-menu h2{{font-size:1.6rem;font-weight:800;color:{acc};margin-bottom:6px;text-align:center}}
.practice-menu .sub{{color:#94a3b8;font-size:.88rem;text-align:center;margin-bottom:28px}}
.practice-card{{display:block;width:100%;text-align:left;background:{rgba_star},.06);border:1.5px solid {dark};border-radius:16px;padding:18px 20px;margin-bottom:14px;cursor:pointer;transition:all .15s;color:#e2e8f0}}
.practice-card:hover{{background:{rgba_star},.15);border-color:{acc}}}
.practice-card .pc-title{{font-size:1.05rem;font-weight:700;color:#e2e8f0;margin-bottom:4px}}
.practice-card .pc-desc{{font-size:.82rem;color:#94a3b8}}
.practice-wrap{{max-width:640px;width:100%}}
.practice-head{{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}}
.practice-score{{color:#94a3b8;font-size:.85rem}}
.match-cols{{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:20px}}
.match-item{{background:{rgba_star},.06);border:1.5px solid {dark};border-radius:12px;padding:12px 14px;margin-bottom:10px;cursor:pointer;font-size:.9rem;color:#e2e8f0;transition:all .15s}}
.match-item:hover{{border-color:{acc}}}
.match-item.selected{{border-color:{acc};background:{rgba_star},.22)}}
.match-item.matched{{background:rgba(16,185,129,.18);border-color:#10b981;color:#6ee7b7;cursor:default}}
.match-item.wrong-flash{{background:rgba(239,68,68,.22);border-color:#ef4444}}
.blank-sentence{{font-size:1.15rem;line-height:1.7;color:#e2e8f0;margin-bottom:26px;text-align:center}}
.blank-sentence .blank{{color:{acc};font-weight:800;letter-spacing:.05em}}
.fib-choices{{display:grid;grid-template-columns:1fr 1fr;gap:12px}}
.aq-word{{font-size:1.7rem;font-weight:800;color:{acc};text-align:center;margin-bottom:4px}}
.aq-pos{{text-align:center;color:#64748b;font-size:.82rem;margin-bottom:18px}}
.aq-prompt{{font-size:1.02rem;color:#e2e8f0;line-height:1.6;margin-bottom:16px;text-align:center}}
.aq-textarea{{width:100%;min-height:120px;background:{rgba_star},.06);border:1.5px solid {dark};border-radius:12px;padding:14px;color:#e8e8f0;font-family:inherit;font-size:.95rem;line-height:1.6;resize:vertical;margin-bottom:14px}}
.aq-textarea:focus{{outline:none;border-color:{acc}}}
.aq-checklist{{background:{rgba_star},.08);border:1px solid {dark};border-radius:12px;padding:16px 18px;margin-top:6px;text-align:left;display:none}}
.aq-checklist.shown{{display:block}}
.aq-checklist ul{{margin:8px 0 0 20px;color:#cbd5e1;font-size:.85rem;line-height:1.8}}
.aq-checklist .aq-def{{color:{acc};font-weight:700;font-size:.85rem;margin-bottom:4px}}
.practice-nav{{display:flex;gap:12px;justify-content:center;margin-top:22px;flex-wrap:wrap}}
"""

    screens_html = f"""
<div id="screen-practice-menu" class="screen hidden">
  <div class="practice-menu">
    <h2>&#x1F4DD; Test Practice</h2>
    <div class="sub">Same format as your real vocab test &mdash; three parts</div>
    <button class="practice-card" id="btn-open-synmatch">
      <div class="pc-title">1. Synonym Match</div>
      <div class="pc-desc">Match each clue to its vocabulary word</div>
    </button>
    <button class="practice-card" id="btn-open-fib">
      <div class="pc-title">2. Fill-in-the-Blank</div>
      <div class="pc-desc">Pick the word that best completes the sentence</div>
    </button>
    <button class="practice-card" id="btn-open-aq">
      <div class="pc-title">3. Answer the Question</div>
      <div class="pc-desc">Practice writing a full-sentence response</div>
    </button>
    <div style="text-align:center"><button class="btn btn-secondary btn-sm" id="btn-practice-back">&#8592; Back</button></div>
  </div>
</div>

<div id="screen-synmatch" class="screen hidden">
  <div class="practice-wrap">
    <div class="practice-head">
      <span class="practice-score" id="sm-score">Matched 0 of 5</span>
      <button class="btn btn-secondary btn-sm" id="btn-sm-back">&#8592; Menu</button>
    </div>
    <div class="match-cols">
      <div id="sm-clues"></div>
      <div id="sm-words"></div>
    </div>
    <div class="practice-nav"><button class="btn btn-primary btn-sm" id="btn-sm-next">New Round &#8594;</button></div>
  </div>
</div>

<div id="screen-fib" class="screen hidden">
  <div class="practice-wrap">
    <div class="practice-head">
      <span class="practice-score" id="fib-score">Question 1 of 8</span>
      <button class="btn btn-secondary btn-sm" id="btn-fib-back">&#8592; Menu</button>
    </div>
    <div class="blank-sentence" id="fib-sentence"></div>
    <div class="fib-choices" id="fib-choices"></div>
    <div class="hint-text" id="fib-hint"></div>
  </div>
</div>

<div id="screen-aq" class="screen hidden">
  <div class="practice-wrap">
    <div class="practice-head">
      <span class="practice-score" id="aq-count">Word 1 of {len(words)}</span>
      <button class="btn btn-secondary btn-sm" id="btn-aq-back">&#8592; Menu</button>
    </div>
    <div class="aq-word" id="aq-word"></div>
    <div class="aq-pos" id="aq-pos"></div>
    <div class="aq-prompt" id="aq-prompt"></div>
    <textarea class="aq-textarea" id="aq-textarea" placeholder="Write your answer in complete sentences..."></textarea>
    <div class="practice-nav">
      <button class="btn btn-secondary btn-sm" id="btn-aq-check">Show Checklist &amp; Definition</button>
      <button class="btn btn-primary btn-sm" id="btn-aq-next">Next Word &#8594;</button>
    </div>
    <div class="aq-checklist" id="aq-checklist">
      <div class="aq-def" id="aq-def"></div>
      <div id="aq-ex" style="color:#94a3b8;font-size:.85rem;font-style:italic;margin-top:6px"></div>
      <ul>
        <li>Did you use the word <b>correctly</b>, matching its real meaning?</li>
        <li>Did you write in <b>complete sentences</b>?</li>
        <li>Did you include enough <b>detail</b> that someone could guess the word's meaning from your answer?</li>
      </ul>
    </div>
  </div>
</div>
"""

    start_button_html = '<div><button class="btn btn-secondary" id="btn-practice-start">&#x1F4DD; Test Practice</button></div>'

    script_js = f"""
var PRACTICE_PROMPTS={prompts_js};
var smState={{clues:[],selClue:null,matched:0,total:0}};
var fibState={{items:[],index:0,score:0}};
var aqIndex=0;

function showPracticeMenu(){{hide('screen-start');hide('screen-quiz');hide('screen-results');hide('screen-flash');show('screen-practice-menu');hide('screen-synmatch');hide('screen-fib');hide('screen-aq');}}

function buildSynMatchRound(){{
  var pool=shuffle(WORDS).slice(0,5);
  var clues=pool.map(function(w){{return {{word:w.word,clue:w.def.split('.')[0]}};}});
  var wordsCol=shuffle(pool.map(function(w){{return w.word;}}));
  smState={{clues:clues,selClue:null,matched:0,total:clues.length}};
  $('sm-score').textContent='Matched 0 of '+smState.total;
  var clueBox=$('sm-clues');clearEl(clueBox);
  clues.forEach(function(c,i){{
    var div=mk('div','match-item',(i+1)+'. '+c.clue);
    div.dataset.word=c.word;
    div.addEventListener('click',function(){{selectClue(div,c.word);}});
    clueBox.appendChild(div);
  }});
  var wordBox=$('sm-words');clearEl(wordBox);
  var letters='ABCDE';
  wordsCol.forEach(function(w,i){{
    var div=mk('div','match-item',letters[i]+') '+w);
    div.dataset.word=w;
    div.addEventListener('click',function(){{selectWord(div,w);}});
    wordBox.appendChild(div);
  }});
}}

function selectClue(el,word){{
  if(el.classList.contains('matched'))return;
  document.querySelectorAll('#sm-clues .match-item').forEach(function(d){{d.classList.remove('selected');}});
  el.classList.add('selected');
  smState.selClue={{el:el,word:word}};
}}

function selectWord(el,word){{
  if(el.classList.contains('matched')||!smState.selClue)return;
  var clue=smState.selClue;
  if(clue.word===word){{
    clue.el.classList.remove('selected');clue.el.classList.add('matched');
    el.classList.add('matched');
    smState.matched++;
    smState.selClue=null;
    $('sm-score').textContent='Matched '+smState.matched+' of '+smState.total;
    if(smState.matched===smState.total)confettiBurst();
  }}else{{
    el.classList.add('wrong-flash');
    setTimeout(function(){{el.classList.remove('wrong-flash');}},450);
  }}
}}

function buildFibRound(){{
  var pool=shuffle(WORDS).slice(0,Math.min(8,WORDS.length));
  fibState={{items:pool,index:0,score:0}};
  renderFib();
}}

function renderFib(){{
  var w=fibState.items[fibState.index];
  $('fib-score').textContent='Question '+(fibState.index+1)+' of '+fibState.items.length;
  var sentence=w.ex.replace(new RegExp(w.word+'[a-z]*','gi'),'<span class="blank">_____</span>');
  $('fib-sentence').innerHTML=sentence;
  var others=shuffle(WORDS.filter(function(x){{return x.word!==w.word;}})).slice(0,3).map(function(x){{return x.word;}});
  var choices=shuffle([w.word].concat(others));
  var box=$('fib-choices');clearEl(box);
  choices.forEach(function(c){{
    var btn=document.createElement('button');
    btn.className='choice-btn';btn.textContent=c;
    btn.addEventListener('click',function(){{fibAnswer(c,btn,w);}});
    box.appendChild(btn);
  }});
  $('fib-hint').textContent='';
}}

function fibAnswer(choice,btn,w){{
  var allBtns=$('fib-choices').querySelectorAll('.choice-btn');
  var correct=choice===w.word;
  allBtns.forEach(function(b){{
    b.disabled=true;
    if(b.textContent===w.word)b.classList.add('correct');
    else if(b===btn&&!correct)b.classList.add('wrong');
  }});
  if(correct){{fibState.score++;burst(btn.getBoundingClientRect().left+btn.offsetWidth/2,btn.getBoundingClientRect().top,'#34d399',18);}}
  else{{$('fib-hint').textContent='\\ud83d\\udca1 The word was "'+w.word+'" \\u2014 '+w.def.split('.')[0]+'.';}}
  setTimeout(function(){{
    fibState.index++;
    if(fibState.index<fibState.items.length)renderFib();
    else{{
      $('fib-sentence').textContent='Round complete! You scored '+fibState.score+' of '+fibState.items.length+'.';
      clearEl($('fib-choices'));
      $('fib-hint').textContent='';
      if(fibState.score===fibState.items.length)confettiBurst();
    }}
  }},1300);
}}

function renderAq(){{
  var w=WORDS[aqIndex];
  $('aq-count').textContent='Word '+(aqIndex+1)+' of '+WORDS.length;
  $('aq-word').textContent=w.word;
  $('aq-pos').textContent=w.pos;
  $('aq-prompt').textContent=PRACTICE_PROMPTS[w.word]||('Use "'+w.word+'" correctly in a few complete sentences.');
  $('aq-textarea').value='';
  $('aq-checklist').classList.remove('shown');
  $('aq-def').textContent=w.word+': '+w.def;
  $('aq-ex').textContent=w.ex;
}}

$('btn-practice-start').addEventListener('click',showPracticeMenu);
$('btn-practice-back').addEventListener('click',showStart);
$('btn-open-synmatch').addEventListener('click',function(){{hide('screen-practice-menu');show('screen-synmatch');buildSynMatchRound();}});
$('btn-open-fib').addEventListener('click',function(){{hide('screen-practice-menu');show('screen-fib');buildFibRound();}});
$('btn-open-aq').addEventListener('click',function(){{hide('screen-practice-menu');show('screen-aq');aqIndex=0;renderAq();}});
$('btn-sm-back').addEventListener('click',function(){{hide('screen-synmatch');show('screen-practice-menu');}});
$('btn-fib-back').addEventListener('click',function(){{hide('screen-fib');show('screen-practice-menu');}});
$('btn-aq-back').addEventListener('click',function(){{hide('screen-aq');show('screen-practice-menu');}});
$('btn-sm-next').addEventListener('click',buildSynMatchRound);
$('btn-aq-check').addEventListener('click',function(){{$('aq-checklist').classList.add('shown');}});
$('btn-aq-next').addEventListener('click',function(){{aqIndex=(aqIndex+1)%WORDS.length;renderAq();}});
"""
    return css, screens_html, start_button_html, script_js
